services:
  - type: web
    name: weather
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m gunicorn weather_project.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
